# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More https://learn.microsoft.com/en-us/azure/app-service/deploy-github-actions
# More https://docs.github.com/en/actions/security-guides/encrypted-secrets

name: Build and deploy Node.js app to Azure Web App - ivyar-web-api

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ivyar-web-api # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: dist/apps/ivyar-web-api # set this to the path to your web app project, defaults to the repository root
  AZURE_WEBAPP_MODULES_PATH: node_modules
  # AZURE_WEBAPP_DEPLOY_ID: ivyar-web-api-deploy-id
  NODE_VERSION: '18.14.0' # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: yarn install and build
        run: |
          yarn install
          yarn run build_all --if-present

      - name: Zip build
        run: zip -r ${{ env.AZURE_WEBAPP_NAME }}.zip ${{ env.AZURE_WEBAPP_MODULES_PATH }} ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: ${{ env.AZURE_WEBAPP_NAME }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        # id: ${{ env.AZURE_WEBAPP_DEPLOY_ID }}
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
